[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink-interfaces/=/home/solimul/Drives/defi-projects/iLend/lib/chainlink-brownie-contracts/contracts/src/v0.8/shared/interfaces/",
    "@forge-std/=/home/solimul/Drives/defi-projects/iLend/lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
