//SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;
import {IERC20} from "../../lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";


contract ProtocolReward {
    error OnlyTreasuryOwnerCanAccess(address user, address iTreasuryOwner);
    // Protocol reward is a percentage of the interest income generated by the deposit pool.
    // It is used to incentivize the protocol and cover operational costs.
    // The protocol reward is calculated as a percentage of the total interest income generated by the deposit pool.
    // The protocol reward is distributed to the protocol's treasury address.

    address public immutable treasurOwnerAddress;
    IERC20 public immutable usdcContract;

    constructor
    (
        IERC20 _usdcContract, 
        address _treasurOwnerAddress
    ) {
        usdcContract = _usdcContract;
        treasurOwnerAddress = _treasurOwnerAddress;
    }

    modifier only_owner(address to) {

        if (to == treasurOwnerAddress) {
            revert OnlyTreasuryOwnerCanAccess(to, treasurOwnerAddress);
        }
        _;
    }
}